title: title
description: theme for kadopoly.github.io
baseurl: ""
url: ""
logo: ""

github:
  repository_url: https://github.com/kadopoly/kadopoly.github.io

paginate: 3
paginate_path: :num

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
