title: kadopoly.github.io.theme
description: theme for kadopoly.github.io
baseurl: ""
url: ""

github:
  repository_url: https://github.com/kadopoly/kadopoly.github.io

paginate: 3
paginate_path: page:num

sass:
  style: expanded

plugins:
  - jekyll-paginate
  - jekyll-feed
