title: 秋色柑橘日和
description: theme for kadopoly.github.io
baseurl: ""
url: ""
logo: /assets/svg/logo.svg

github:
  repository_url: https://github.com/kadopoly/kadopoly.github.io

paginate: 3
paginate_path: :num

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed

exclude:
  - libs
